version: "3.8"
services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - "./redis-data:/data"
    command: redis-server
  node-server1:
    build: ./hollow-server
    ports:
      - "9091"
    depends_on:
      - redis
  node-server2:
    build: ./hollow-server
    ports:
      - "9091"
    depends_on:
      - redis
  node-server3:
    build: ./hollow-server
    ports:
      - "9091"
    depends_on:
      - redis
  node-server4:
    build: ./hollow-server
    ports:
      - "9091"
    depends_on:
      - redis
  node-server5:
    build: ./hollow-server
    ports:
      - "9091"
    depends_on:
      - redis
  envoy:
    build: ./envoy
    ports:
      - "3000:8080"
    platform: linux/amd64
    depends_on:
      - node-server1
      - node-server2
      - node-server3
      - node-server4
      - node-server5
    links:
      - node-server1
      - node-server2
      - node-server3
      - node-server4
      - node-server5
  cadvisor:
    image: gcr.io/cadvisor/cadvisor-arm64:v0.47.0
    container_name: cadvisor
    # userns_mode: "host"
    # pid: "host"
    # privileged: true
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      # - /var/run:/var/run:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw # for macos
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
